// Generated by CoffeeScript 1.6.3
/*
Copyright (c) 2013 Juhani Imberg

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/


(function() {
  var fs, modman, path;

  fs = require("fs");

  path = require("path");

  modman = function() {
    var o;
    o = {};
    o.loaded = [];
    o.available = [];
    o.timeouts = {};
    o.modulePath = "";
    o.irc = null;
    o.hasInit = false;
    o.init = function(irc, modulePath) {
      var _this = this;
      this.irc = irc;
      this.modulePath = modulePath || irc.config.modulePath;
      this.hasInit = true;
      return fs.watch(this.modulePath, function(event, filename) {
        var delay;
        delay = function(ms, func) {
          return setTimeout(func, ms);
        };
        if (typeof o.timeouts['filename'] !== "undefined") {
          clearTimeout(o.timeouts['filename']);
        }
        return o.timeouts['filename'] = delay(1000, function() {
          var name;
          console.log("MM.EVENT is " + event);
          console.log("MM.FILENAME is " + filename);
          name = filename.split(".");
          if (name.slice(1).join(".") === "module.js") {
            if (event === "change") {
              return _this.load(name[0]);
            }
          }
        });
      });
    };
    o.refresh = function() {
      var error, files, i, parts, tmp, _i, _len;
      try {
        tmp = [];
        files = fs.readdirSync(this.modulePath);
        for (_i = 0, _len = files.length; _i < _len; _i++) {
          i = files[_i];
          parts = i.split(".");
          if (parts.slice(1).join(".") === "module.js") {
            tmp.push(parts[0]);
          }
        }
        return this.available = tmp;
      } catch (_error) {
        error = _error;
        return console.log("ERROR " + error);
      }
    };
    o.loadAll = function() {
      var error, i, _i, _len, _ref, _results;
      this.refresh();
      console.log(this.available);
      try {
        _ref = this.available;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          i = _ref[_i];
          _results.push(this.load(i));
        }
        return _results;
      } catch (_error) {
        error = _error;
        return console.log("ERROR " + error);
      }
    };
    o.hardReload = function() {
      this.loaded = [];
      this.irc.hooks = [];
      return this.loadAll();
    };
    o.isLoaded = function(name) {
      var i, _i, _len, _ref;
      _ref = this.loaded;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        i = _ref[_i];
        if (i.name === name) {
          return true;
        }
      }
      return false;
    };
    o.resolveName = function(name) {
      var i, _i, _len, _ref;
      _ref = this.loaded;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        i = _ref[_i];
        if (i.name === name) {
          return i;
        }
      }
      return null;
    };
    o.god = function(name) {
      var g;
      g = this.resolveName("god");
      if (g !== null) {
        return g.module.auth(name);
      }
    };
    o.load = function(name) {
      var error, module, pat;
      try {
        if (this.irc.config.disabledModules.indexOf(name) !== -1) {
          return;
        }
        if (this.isLoaded(name)) {
          return this.reload(name);
        } else {
          pat = path.resolve(this.modulePath, name + ".module.js");
          delete require.cache[pat];
          module = require(pat);
          module = module[name];
          module.init(this.irc);
          this.loaded.push({
            name: name,
            path: pat,
            module: module
          });
          console.log("MM.LOAD " + name);
          if (this.available.indexOf(name) === -1) {
            return this.available.push(name);
          }
        }
      } catch (_error) {
        error = _error;
        return console.log("ERROR " + error);
      }
    };
    o.unload = function(name) {
      var error, i, pos;
      try {
        i = this.resolveName(name);
        if (i !== null) {
          pos = this.loaded.indexOf(i);
          i.module.deinit(this.irc);
          delete require.cache[i.path];
          this.loaded.splice(pos, 1);
          return console.log("MM.UNLOAD " + name);
        }
      } catch (_error) {
        error = _error;
        return console.log("ERROR " + error);
      }
    };
    o.reload = function(name) {
      var error;
      try {
        this.unload(name);
        return this.load(name);
      } catch (_error) {
        error = _error;
        return console.log("ERROR " + error);
      }
    };
    o.reloadAll = function(name) {
      var error, i, _i, _len, _ref, _results;
      try {
        _ref = this.loaded;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          i = _ref[_i];
          _results.push(this.reload(i.name));
        }
        return _results;
      } catch (_error) {
        error = _error;
        return console.log("ERROR " + error);
      }
    };
    o.disable = function(name) {
      var pos;
      pos = this.irc.config.disabledModules.indexOf(name);
      if (pos === -1) {
        this.irc.config.disabledModules.push(name);
        return this.unload(name);
      }
    };
    o.enable = function(name) {
      var pos;
      pos = this.irc.config.disabledModules.indexOf(name);
      if (pos !== -1) {
        this.irc.config.disabledModules.splice(pos, 1);
        return this.load(name);
      }
    };
    o.getLoaded = function() {
      var i, tmp, _i, _len, _ref;
      tmp = [];
      _ref = this.loaded;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        i = _ref[_i];
        tmp.push(i.name);
      }
      return tmp;
    };
    o.getAvailable = function() {
      this.refresh();
      return this.available;
    };
    o.getDisabled = function() {
      return this.irc.config.disabledModules;
    };
    return o;
  };

  exports.modman = new modman;

}).call(this);
