// Generated by CoffeeScript 1.6.3
(function() {
  var mui;

  mui = function() {
    var o;
    o = {};
    o.lastTime = 0;
    o.hookId = -1;
    o.init = function(irc) {
      return o.hookId = irc.hook('PRIVMSG', function(args) {
        var now, rec;
        if (args.message.toLowerCase().substring(0, 4) === "mui.") {
          now = Date.now();
          if (now - 10000 < o.lastTime) {
            return;
          }
          o.lastTime = now;
          rec = args.respond;
          if (args.message.toLowerCase().split(" ")[1] === irc.config.nick) {
            return irc.send('PRIVMSG', rec, ':Mui. ' + args.sender);
          } else {
            return irc.send('PRIVMSG', rec, ':Mui.');
          }
        }
      });
    };
    o.deinit = function(irc) {
      return irc.dehook(this.hookId);
    };
    return o;
  };

  exports.mui = new mui;

}).call(this);
