// Generated by CoffeeScript 1.6.3
(function() {
  var irc, net, stdin, sys;

  net = require("net");

  sys = require("sys");

  stdin = process.openStdin();

  stdin.addListener("data", function(d) {
    var message;
    message = d.toString().substring(0, d.length - 2);
    if (message.indexOf(".") === 0) {
      return irc.command(message.substring(1));
    } else {
      return irc.send(message);
    }
  });

  irc = {
    buffer: "",
    hooks: []
  };

  irc.config = {
    nick: "uno",
    realname: "Uno Not One",
    network: "irc.paivola.fi:6667",
    encoding: "utf8"
  };

  irc.hook = function(action, callback) {
    return this.hooks.push({
      callback: callback,
      action: action
    });
  };

  irc.fire = function(action, args) {
    var i, _i, _len, _ref, _results;
    _ref = this.hooks;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      i = _ref[_i];
      if (i.action === action) {
        _results.push(i.callback(args));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  irc.command = function(com) {
    var args, command;
    console.log("command " + com);
    command = com[0].toLowerCase();
    args = com.slice(1);
    switch (command) {
      case 'q':
      case 'e':
      case 'quit':
      case 'exit':
        return irc.send("QUIT");
      case 'r':
      case 'c':
      case 'reconnect':
      case 'connect':
        return irc.connect();
      case 'name':
      case 'nick':
      case 'rename':
      case 'renick':
        return irc.name(args[0]);
    }
  };

  irc.name = function(newName) {
    return this.send('NICK ' + newName);
  };

  irc.connect = function() {
    var a, addr, port;
    this.socket.setEncoding(this.config.encoding);
    this.socket.setNoDelay();
    a = this.config.network.split(":");
    port = a[1];
    addr = a[0];
    return this.socket.connect(port, addr);
  };

  irc.send = function(arg1) {
    var i, message, _i, _len;
    message = [];
    for (_i = 0, _len = arguments.length; _i < _len; _i++) {
      i = arguments[_i];
      if (i) {
        message.push(i);
      }
    }
    message = message.join(' ');
    sys.puts('< ' + message);
    message = message + "\r\n";
    return this.socket.write(message, this.config.encoding);
  };

  irc.parse = function(message) {
    var match, params, parsed;
    match = message.match(/(?:(:[^\s]+) )?([^\s]+) (.+)/);
    parsed = {
      prefix: match[1],
      command: match[2]
    };
    params = match[3].match(/(.*?) ?:(.*)/);
    if (params) {
      params[1] = params[1] ? params[1].split(' ') : [];
      params[2] = params[2] ? [params[2]] : [];
      params = params[1].concat(params[2]);
    } else {
      params = match[3].split(' ');
    }
    parsed.params = params;
    return parsed;
  };

  irc.socket = new net.Socket;

  irc.socket.on('connect', function() {
    irc.send('NICK ' + irc.config.nick);
    return irc.send('USER', irc.config.nick, '0 *:' + irc.config.nick, irc.config.realname);
  });

  irc.socket.on('data', function(data) {
    var message, offset;
    this.buffer = this.buffer + data;
    while (this.buffer.length > 0) {
      offset = this.buffer.indexOf("\r\n");
      if (offset < 0) {
        return;
      }
      message = this.buffer.substr(0, offset);
      this.buffer = this.buffer.substr(offset + 2);
      sys.puts('> ' + message);
      message = irc.parse(message);
      if (message !== false) {
        irc.handleMessage(message);
      }
    }
  });

  irc.handleMessage = function(message) {
    var args, chat, reciever, sender;
    console.log(message);
    switch (message.command) {
      case 'PING':
        return this.send('PONG', ':' + message.params[0]);
      case 'PRIVMSG':
        chat = message.params[1];
        reciever = message.params[0];
        sender = message.prefix.split("!")[0].substring(1);
        args = {
          message: chat,
          sender: sender,
          reciever: reciever,
          isChannel: reciever.indexOf("#") === 0
        };
        return irc.fire('PRIVMSG', args);
    }
  };

  irc.hook('PRIVMSG', function(args) {
    if (args.message.toLowerCase().substring(0, 4) === "mui.") {
      if (args.message.toLowerCase().split(" ")[1] === irc.config.nick) {
        return irc.send('PRIVMSG', args.reciever, ':Mui. ' + args.sender);
      } else {
        return irc.send('PRIVMSG', args.reciever, ':Mui.');
      }
    }
  });

  irc.connect();

}).call(this);
